// <auto-generated />
namespace DevicesRequest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class sort_Model_RequestItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sort_Model_RequestItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201809110849266_sort_Model_RequestItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
