// <auto-generated />
namespace DevicesRequest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_Data_New : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Data_New));
        
        string IMigrationMetadata.Id
        {
            get { return "201809110834071_add_Data_New"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
