// <auto-generated />
namespace DevicesRequest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Change_requredPosition01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_requredPosition01));
        
        string IMigrationMetadata.Id
        {
            get { return "201810070817220_Change_requredPosition01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
